name: Flutter Build test

on: [ push, pull_request ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: 'Set Flutter Version Latest'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest

      - name: 'Checkout Flutter latest'
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout latest;
          flutter --version;

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
