name: Flutter Build test

on: [ push, pull_request ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: 'Set Flutter 3.10.6'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6

      - name: 'Checkout Flutter 3.10.7'
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.10.7;
          flutter --version;

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
